name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

jobs:
  CLAassistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == '@[CLA bot] recheck CLA' || github.event.comment.body == '@[CLA bot] I have read the CLA Document and I hereby sign the CLA.') || github.event_name == 'pull_request_target'
        uses: cla-assistant/github-action@v2.1.3-beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN : ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          path-to-signatures: 'signatures/qir-alliance.github.io/cla.json'
          path-to-document: 'https://github.com/qir-alliance/.github/blob/main/Contributor_License_Agreement.md' # the actual CLA that a contributor agrees to
          branch: 'main' # branch must not be protected
          allowlist: user1,bot*
          remote-organization-name: qir-alliance
          remote-repository-name: data_storage
          lock-pullrequest-aftermerge: true
          custom-allsigned-prcomment: '**[CLA bot]** All Contributors have signed the CLA.'
          # TODO: edit the bot messages to link to the CLA
          custom-notsigned-prcomment: '**[CLA bot]** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/qir-alliance/.github/blob/main/Contributor_License_Agreement.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment with the following content:<br/>---<br/>***@[CLA bot] I have read the CLA Document and I hereby sign the CLA.***<br/>---<br/><sub>You can re-trigger this bot by commenting ***@[CLA bot] recheck CLA*** in this Pull Request.</sub>'
          custom-pr-sign-comment: 'I have read the Contributor License Agreement and I hereby accept the Terms.'
